disablePathToLower: true
languageCode: en-us
title: xkyle.com
theme: hugo-flex
permalinks:
  post: /:slug/
relativeURLs: true
publishDir: docs
pygmentsCodeFences: true

markup:
  goldmark:
    renderer:
      unsafe: true
